### PR TITLE
Fix #586: Allow v3 configuration of master public key

### LINKED ISSUE #586: Allow v3 configuration of master public key
### Affected product(s) and version(s)

develop

### Environment

local

### Steps to reproduce, current result, expected result

The newest version expects configuration using `v4/application/detail`, but it may be desirable to still use the old `v3` configuration format which includes only P-256 master public key.

### Log output

_No response_

### PR DESCRIPTION
**Pull request by romanstrobl**
For `v3` we should not validate presence of all keys, because some of them are added in `v4`.

### CODE REVIEW

File: powerauth-java-cmd-lib/src/main/java/com/wultra/security/powerauth/lib/cmd/util/ConfigurationUtil.java [hunk 1]
```diff
@@ -168,10 +168,6 @@ private static PublicKey convertMasterPublicKeyEC(EcCurve ecCurve, String master
                 stepLogger.writeDoneFailed("master-key-failed");
                 System.exit(1);
             }
-        } else {
```
Comment (jnpsk) [inline powerauth-java-cmd-lib/src/main/java/com/wultra/security/powerauth/lib/cmd/util/ConfigurationUtil.java:171]: For the code readability, I would switch the condition, so most of the method's code is not in an if-condition.

**Review by jnpsk — APPROVED** [review]
Looks ok.
Personally, I would return `null` already in callers (the getter methods), just because of the code clarity.
